spring:
  datasource:
    url: jdbc:h2:file:./data/currencyExchange;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  messages:
    basename: messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update   # update schema without dropping data
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  # Feign client configs
  cloud:
    openfeign:
      okhttp:
        enabled: true
      circuitbreaker:
        enabled: true
      client:
        config:
          oanda-api:
            url: https://fxds-public-exchange-rates-api.oanda.com
            loggerLevel: FULL
            connectTimeout: 25000
            readTimeout: 25000
            followRedirects: false